.github/workflows/rsp-dev-gke-tf.yaml
Known issue with the Google GKE module and 0.13.x using counts. Work around has been to downgrade to terraform 0.12.29
=> changed terraform_version from 0.13.5 to 0.12.29

environment/deployments/science-platform/env/integration.tfvars, environment/deployments/science-platform/main.tf, environment/deployments/science-platform/variables.tf
For the science-platform-int environment, moved the firewall rule out of the module and into the tfvars.
Found some unused variables for GKE that were moved into the GKE module and are no longer needed.
=> Rsp int fw update

environment/deployments/science-platform/env/dev.tfvars
Moved the custom firewall rule into the tfvars file. 
Updated the rule to allow ranges from 172.16.0.0/28
=> moved fw into tfvars

environment/foundation/1-org/variables.tf
added project viewer to org monitoring admin and viewer
=> added project viewer to org monitoring admin and viewer

environment/deployments/qserv/env/dev.tfvars, environment/deployments/qserv/env/integration.tfvars, environment/deployments/qserv/main.tf, environment/deployments/qserv/variables.tf, modules/project_vpc/main.tf
adding additional budgeting variables from the parent module into the child modules.
=> updates for budgets in tfvars

environment/deployments/science-platform/env/dev.tfvars, environment/deployments/science-platform/env/integration.tfvars, environment/deployments/science-platform/main.tf, environment/deployments/science-platform/variables.tf
Presented the budget amount and alerts to the child module.
=> add budgets and budget alerts

.github/workflows/terraform-google-groups.yaml, environment/foundation/google_groups/env/groups.tfvars, environment/foundation/google_groups/main.tf, environment/foundation/google_groups/outputs.tf, environment/foundation/google_groups/providers.tf, environment/foundation/google_groups/variables.tf, modules/google_groups/main.tf, modules/google_groups/outputs.tf, modules/google_groups/readme.md, modules/google_groups/variables.tf
New pipeline for google groups
=> New group module

environment/deployments/butler-repo/env/dev.tfvars, environment/deployments/butler-repo/main.tf
Follow up with the postgres issue
=> DM-28533: Add more permissions to gcp-butler-administrators 

environment/deployments/panda/env/dev-gke.tfvars
Redo the cancelled operation from
https://github.com/lsst/idf_deploy/actions/runs/501965929
=> Kick Panda's GKE with a null change

environment/deployments/butler-repo/env/dev.tfvars, environment/deployments/butler-repo/main.tf
=> DM-28761: Re-create the postgres instance

environment/deployments/panda/env/dev.tfvars
=> DM-29287: Enable IAP API in panda-dev

environment/deployments/panda/env/dev.tfvars, environment/deployments/panda/main.tf
A short-term solution for the submission machine
=> DM-29287: Add a VM to panda-dev

environment/deployments/panda/env/dev.tfvars, environment/deployments/panda/main.tf
This reverts commit c0551f67fe34e23b1906be4bf10a445cb616e5db.
=> DM-29287: Revert "Add a VM to panda-dev"

environment/deployments/panda/env/dev.tfvars, environment/deployments/panda/variables.tf
=> DM-29287: Add more permissions in panda-dev

.github/workflows/rsp-dev-cloudsql-tf.yaml, .github/workflows/rsp-int-cloudsql-tf.yaml, .github/workflows/rsp-stable-cloudsql-tf.yaml, modules/cloudsql/postgres-sql/main.tf, modules/cloudsql/postgres-sql/variables.tf
- Bump timeouts for creating CloudSQL resources
- Trigger CloudSQL workflows on more changes
=> [DM-28120] Increase timeouts for CloudSQL actions

environment/deployments/data-curation/env/production.tfvars, environment/deployments/data-curation/main.tf
for the main DP0.1 butler repo bucket. 
Without this, butler commands don't work.
=> DM-29773: Add a legacyBucketReader role to the butler sa

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Make  -int the same as -stable and -dev
=> DM-29134: Disable SSL requirement in science-platform-int

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Apply the setting changes already applied to dev.
=> [DM-30880] Update Science Platform database settings on int

environment/deployments/science-platform/env/production-cloudsql.tfvars
Apply the setting changes already applied to dev.
=> [DM-30880] Update Science Platform database settings on prod

environment/deployments/science-platform/env/production-cloudsql.tfvars
Missed this before I merged, thanks.
=> [DM-30880] Fix comment for production-cloudsql.tfvars

environment/deployments/science-platform/env/integration-gke.tfvars, environment/deployments/science-platform/gke/main.tf, environment/deployments/science-platform/gke/variables.tf
See if this is causing our network reset problems.
=> [DM-30906] Disable network policy on data-int

environment/deployments/science-platform/env/integration-gke.tfvars
The new version of Kubernetes should correctly support it without
the bug that we previously ran into.
=> [DM-31173] Re-enable NetworkPolicy support on IDF int

environment/deployments/qserv/env/dev.tfvars, environment/deployments/qserv/main.tf, environment/deployments/qserv/variables.tf, modules/firewall/readme.md
Adding a second firewall rule for all environments. Adding to qserv-dev first.
=> Fix qserv dev firewall

environment/deployments/science-platform/env/integration-gke.tfvars
=> [DM-31173] Force Terraform to run on data-int

environment/deployments/panda/env/dev.tfvars, environment/deployments/panda/main.tf, environment/deployments/panda/variables.tf, modules/bucket/main.tf, modules/bucket/variables.tf, modules/cloud_nat/main.tf, modules/cloud_nat/variables.tf
Replace Cloud NAT with an auto-ip allocation option
=> Fix pandas nat

environment/foundation/1-org/1-org.tfvars
Phase 1. Create a top level folder called EPO.
=> add new top level folder: EPO

environment/foundation/1-org/1-org.tfvars
A first step for DM-31299 and DM-31300, which add alert broker infrastructure to the IDF.
=> Add Alert Production folder to 1-org/1-org.tfvars

environment/foundation/1-org-b/1-org-b.tfvars, environment/foundation/1-org-b/data.tf, environment/foundation/1-org-b/sub_folders.tf, environment/foundation/1-org-b/variables.tf
=> Add Alert Production subfolders

environment/deployments/science-platform/env/integration-gke.tfvars
Similar to the existing setting for dev but one day later.
=> [DM-31280] Set maintenance window for int GKE cluster

environment/deployments/science-platform/env/integration-gke.tfvars, environment/deployments/science-platform/env/production-gke.tfvars
Follow the same pattern as dev and int.  Also fix the start and
end times for int so that they fall on a Thursday (I think that
part is ignored when there's a recurrence, but it looked weird).
=> [DM-31280] Set maintenance window on science-platform-prod

environment/deployments/science-platform/env/production-gke.tfvars, environment/deployments/science-platform/gke/variables.tf
This has been running on IDF int for several months now with no
issues.
=> [DM-31173] Re-enable NetworkPolicy for IDF prod

environment/deployments/panda/env/dev.tfvars
Going to change this in two phases.
P1 - Change the overlapping CIDR range - 10.138.16.0/20 -> 10.138.128.0/20
P2 - Change the primary CIDR range - 10.138.0.0/23 -> 10.138.0.0/18
=> changing the overlapping secondary range first

environment/deployments/panda/env/dev.tfvars
First remove the secondary cidr range - 10.138.16.0/20
=> remove secondary cidr

environment/deployments/panda/env/dev.tfvars
Add the new cidr range - 10.138.128.0/20
=> add new secondary cidr range

environment/deployments/science-platform/env/integration-cloudsql.tfvars
This will create the vo-cutouts database on data-int.
=> [DM-32386] Resync the data-int CloudSQL configuration

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Trigger applying the new GCS bucket resources in data-int as well.
=> [DM-33494] Create new cutouts GCS bucket in data-int

environment/deployments/panda/env/dev.tfvars
Added in gcr and artifact registry roles for service account per Shuwei request
=> SA Role additions

environment/deployments/qserv/env/dev.tfvars
Added port for qserv operator to connect from API server to nodes.
=> added port for qser operator

environment/foundation/1-org-b/1-org-b.tfvars, environment/foundation/1-org-b/variables.tf
Add dns domain admin rights to shared services
=> Frossie patch 1

environment/deployments/science-platform/env/production.tfvars
Create the crawlspace service account there as well.
=> Force Terraform run for science-platform-stable

environment/deployments/panda/env/dev-gke.tfvars, environment/deployments/panda/gke/main.tf, environment/deployments/panda/gke/variables.tf
Removing CSI driver, load balancing, workload identity.  Changing to node local DNS cache.
=> Update extra high mem cluster

environment/deployments/panda/env/dev-gke.tfvars, environment/deployments/panda/gke/main.tf
removing workload identity, csi driver.  Adding in dns cache.  Adjusting maintenace schedules.
=> adjusting other panda cluster settings

environment/deployments/panda/env/dev-gke.tfvars, environment/deployments/panda/gke/main.tf, environment/deployments/panda/gke/variables.tf
removing workload identity, csi driver, and load balancing.  Adding dns cache.
=> changes to moderatemem and development cluster

environment/deployments/panda/env/dev-gke.tfvars, environment/deployments/panda/gke/main.tf, environment/deployments/panda/gke/variables.tf
Updated node pool names to match cluster.  Mapped service accounts.
=> updated service accounts and names

environment/deployments/science-platform/env/integration.tfvars, environment/deployments/science-platform/main.tf
Trying to follow Dan's instructions
=> [DM-26505] Workload identity

environment/deployments/science-platform/env/integration.tfvars, environment/deployments/science-platform/main.tf
Change module to project iam member from service account member for DNS validator SA
=> DNS validator SA. Update module for project iam member

environment/deployments/roundtable/env/dev-cloudsql.tfvars, environment/deployments/roundtable/env/dev-gke.tfvars, environment/deployments/roundtable/env/production-cloudsql.tfvars, environment/deployments/roundtable/env/production-gke.tfvars
Enables the Roundtable GKE clusters and sets the project ID for related Cloud SQL.
=> DM-37659: Configure Roundtable GKE clusters

environment/deployments/roundtable/env/dev.tfvars, environment/deployments/roundtable/env/production.tfvars, environment/deployments/roundtable/main.tf
This reserves a public IP for the roundtable ingresses.
=> DM-37659: Add a public IP for roundtable

environment/deployments/science-platform/firestore/env/integration.tfvars
Change app name to update label.  Needed for filter on vpc peer to Qserv.
=> Firestore Int Label update

environment/deployments/roundtable/env/production-cloudsql.tfvars, environment/deployments/science-platform/env/integration-cloudsql.tfvars, environment/deployments/science-platform/env/production-cloudsql.tfvars
Tell Terraform to reapply configurations to roundtable, data-int, and data to pick up the changes to the Gafaelfawr service accounts.
=> DM-42384: Update Gafaelfawr service accounts

environment/deployments/roundtable/env/dev.tfvars, environment/deployments/roundtable/env/production.tfvars, environment/deployments/roundtable/main.tf, environment/deployments/roundtable/variables.tf
Change from iam binding to iam member which is non authorative for vault and git lfs. Change casing to underscores to be consistent. Ran terraform fmt to adjust spacing. Adjust serial to run terraform plan.
=> Roundtable Vault and LFS IAM Fixes

.gitignore, environment/foundation/1-org-b/1-org-b.tfvars
Create folders for new Demo environment parallel to dev/int/prod
=> tickets/DM-43454-folders: Add new "Demo" IDF environment

.github/workflows/rsp-filestore-dir.yaml
Replace GKE credential setup with GitHub action because kubectl authentication changed in kubernetes 1.26
=> Filestore Directory Provisioning GKE Authentication Fix

.github/workflows/rsp-filestore-dir.yaml
Fix region value as it was referencing value that was not defined.
=> Firestore Directory Provisioning Region Fix

.github/workflows/rsp-demo-gke-tf.yaml, .github/workflows/rsp-demo-proj-tf.yaml, NEW_ENVIRONMENT.md
Use more limited SAs for base/gke workflows for rsp/demo
=> tickets/DM-43454-workflows: restrict SAs for GHA

environment/deployments/science-platform/env/demo-cloudsql.tfvars, environment/deployments/science-platform/env/demo.tfvars, environment/deployments/science-platform/main.tf
Add butler DB for demo.lsst.cloud
=> tickets/DM-43454-butlerdb: Add butler DB to demo environment

environment/deployments/qserv/env/prod-vpcpeer2.tfvars
Increase serial to trigger VPC peering build from RSP dev to QServ Prod.
=> DM-44089: RSP Dev VPC Peering to Qserv Prod

environment/deployments/qserv/env/prod-vpcpeer3.tfvars
Add RSP int  to Qserv Prod VPC peering.
=> DM-44089: RSP INT to Qserv Prod VPC Peeting

environment/deployments/science-platform/cloudsql/main.tf, environment/deployments/science-platform/cloudsql/variables.tf, environment/deployments/science-platform/env/dev-cloudsql.tfvars
Removes butler registry not in use and replaces with butler dp02 registry.  Changes structure to support multiple butler registries in the future and to separate the variables for the science platform database.
=> DM-46039: Butler Registry DP02 Modules Update and Dev Deployment

.github/workflows/rsp-stable-cloudsql-tf.yaml, environment/deployments/science-platform/env/production-cloudsql.tfvars
Terraform upgrade for RSP CloudSQL stable.  Butler DP02 Registry set to disabled so it is not created.
=> DM-47492:  RSP CloudSQL Stable

environment/deployments/data-curation/backend.tf, environment/deployments/data-curation/main.tf
Update google provider version.  Add location to bucket name since formatting changed with newer Google provided bucket resource.
=> DM-47492: Data Curation Project

environment/deployments/data-curation/variables.tf
Update data curation billing ID to the slac billing ID.
=> DM-47492: Update Data Curation Billing ID

environment/deployments/alert-prod/variables.tf, environment/deployments/butler-repo/variables.tf, environment/deployments/panda/variables.tf, environment/deployments/qserv/variables.tf, environment/deployments/roundtable/variables.tf, environment/deployments/science-platform/firestore/variables.tf, environment/deployments/science-platform/variables.tf, environment/foundation/constants/constants.tf
Update from AURA to SLAC Billing ID in constants and variables.
=> DM-48922: AURA to SLAC Billing ID

.github/workflows/roundtable-dev-cloudsql-tf.yaml, environment/deployments/roundtable/cloudsql/backend.tf, environment/deployments/roundtable/cloudsql/main.tf, environment/deployments/roundtable/env/dev-cloudsql.tfvars, environment/deployments/roundtable/env/production-cloudsql.tfvars, modules/cloudsql/postgres-private_50/main.tf, modules/cloudsql/postgres-private_50/variables.tf
Trigger terraform to compute new Ook CloudSQL support originally added in #565.
=> DM-49491: Increment Roundtable CloudSQL

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Apply the changes to Gafaelfawr service account configuration on idfint as well.
=> DM-49524: Update Gafaelfawr configuration for idfint

environment/deployments/roundtable/cloudsql/variables.tf, environment/deployments/roundtable/env/dev-cloudsql.tfvars
Upgrade the Cloud SQL database on roundtable-dev to PostgreSQL 14.
=> DM-49696: Upgrade Cloud SQL on roundtable-dev

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Apply pending Terraform changes on idfint, which include the upgrade of Cloud SQL to PostgreSQL 14.
=> DM-49696: Upgrade PostgreSQL on idfint

environment/deployments/science-platform/env/production-cloudsql.tfvars
Apply pending Terraform changes on idfprod, which include the upgrade of Cloud SQL to PostgreSQL 14.
=> DM-49696: Upgrade PostgreSQL on idfprod

environment/deployments/science-platform/cloudsql/variables.tf, environment/deployments/science-platform/env/dev-cloudsql.tfvars
Upgrade the PostgreSQL version of Cloud SQL for idfdev to 15.
=> DM-49696: Upgrade PostgreSQL for idfdev

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Pick up the upgrade of the Cloud SQL PostgreSQL version to 15.
=> DM-49696: Resync idfint Cloud SQL

environment/deployments/science-platform/env/production-cloudsql.tfvars
Pick up the upgrade of the Cloud SQL PostgreSQL version to 15.
=> DM-49696: Resync idfprod Cloud SQL

environment/deployments/science-platform/env/integration-cloudsql.tfvars
Resynchronize with the current Cloud SQL Terraform configuration.
=> DM-49696: Upgrade idfint Cloud SQL to PostgreSQL 16

environment/deployments/science-platform/env/production-cloudsql.tfvars
Resynchronize with the current Cloud SQL Terraform configuration.
=> DM-49696: Upgrade idfprod Cloud SQL to PostgreSQL 16

environment/deployments/science-platform/env/integration.tfvars, environment/deployments/science-platform/netapp_volumes.tf
Only put /home on int for now.
=> tickets/DM-48780: only /home in int for now

environment/deployments/science-platform/cloudsql/main.tf, environment/deployments/science-platform/env/integration-cloudsql.tfvars, modules/alloydb/main.tf, modules/alloydb/variables.tf
Fix an issue where AlloyDB would not deploy due to a missing project ID setting.
=> DM-50677: Fix failure to deploy AlloyDB

environment/deployments/roundtable/env/dev-gke.tfvars, environment/deployments/roundtable/gke/backend.tf, environment/deployments/roundtable/gke/main.tf, environment/deployments/roundtable/gke/variables.tf, modules/gke/main.tf, modules/gke/variables.tf
Updates GKE module to more recent version.  Adds support for enabling FUSE driver in GKE and enables in dev.
=> DM-50064: Roundtable GKE version update and Fuse Driver

environment/deployments/roundtable/env/production-cloudsql.tfvars
Upgrade Cloud SQL to PostgreSQL 16, previously applied to roundtable-dev.
=> DM-49696: Synchronize Cloud SQL for roundtable

environment/deployments/roundtable/env/production.tfvars
Bump serial to create EUPS workload identity service account in prod.
=> EUPS Workload Identity Service Account

environment/deployments/roundtable/cloudsql/main.tf, environment/deployments/roundtable/env/dev-cloudsql.tfvars, environment/deployments/science-platform/cloudsql/main.tf, environment/deployments/science-platform/env/dev-cloudsql.tfvars, environment/deployments/science-platform/env/integration-cloudsql.tfvars
Oops, forgot these when I added the config for the new Grafana databases.
=> DM-50602: Grafana Cloud SQL proxy service accounts

environment/deployments/roundtable/env/production-cloudsql.tfvars, environment/deployments/science-platform/env/production-cloudsql.tfvars
Create the [Grafana Postgres DBs](https://github.com/lsst/idf_deploy/pull/637) in production environments.
=> DM-50602: Grafana Postgres DBs (production)

environment/deployments/science-platform/env/dev.tfvars
...and I forgot to bump the serial for idfdev :( :( :( :( :(
=> DM-51084: Fix grafana service account permissions in idfdev
