lsst/idf_deploy

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
- modules/gke/variables.tf
Make the default release channel REGULAR, and set the release
channel to the dev environment to RAPID so that we can use it for
early testing of Kubernetes compatibility.
> [DM-27867] Set the release channel on GKE environments

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/env/integration-gke.tfvars
- environment/deployments/science-platform/env/integration.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/variables.tf
- modules/compute/variables.tf
- modules/filestore/variables.tf
- modules/gke/variables.tf
The old style node labels did not work--I ended up getting all labels in all pools.  So now I am also explicitly overriding "all" and we will see if that works.  I am shrinking the dask node pool down to zero size, but leaving the pool because I am sure we will want to scale it back up in future.
> Scale dask pool back down and make SSD default fileshare

- environment/deployments/science-platform/backend.tf
- environment/deployments/science-platform/env/dev.tfvars
Pinning the google provider to a previous version. The current release of 3.54 breaks if the project has a budget assigned.
> pinned provider to 3.51

- environment/deployments/butler-repo/env/dev.tfvars
- modules/cloudsql/postgres-private/main.tf
- modules/cloudsql/postgres-private/variables.tf
It seems[ the upstream default](https://github.com/terraform-google-modules/terraform-google-sql-db/blob/master/modules/postgresql/variables.tf#L240) is 10m
> DM-28881: Increase default timeout for postgres creation or updates

- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/env/integration.tfvars
- environment/deployments/science-platform/env/production.tfvars
The firewall rule has to allow connections from the Kubernetes
master to the pods in the cluster so that it can query validation
webhooks.  The IP range in the rule for integration was copied from
dev, instead of matching the master IP range for integration (which
is not the same).
> [DM-28891] Fix data-int IP range for validation webhooks

- environment/deployments/panda/env/dev-cloudsql.tfvars
The last merge didn't create the postgres yet as the tier string was incorrect.
> DM-29015: Use high-mem db type for panda

- environment/foundation/1-org-b/1-org-b.tfvars
Grant the roles/oauthconfig.editor role to Science Platform
administrators so that I can experiment with Google OAuth
authentication for Argo CD.
> [DM-28900] Add OAuth to Science Platform administrators

- environment/deployments/panda/env/dev.tfvars
- environment/deployments/panda/variables.tf
Based on [this](https://cloud.google.com/compute/docs/access/iam#connectinginstanceadmin ) roles/compute.instanceAdmin.v1 should provide enough permissions.
> DM-29185: Add compute.instanceAdmin.v1 role to panda-admin group

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
We need this to be able to do persistent volume snapshots.  Will
change the default to true and enable it on the other science
platform clusters in a follow-up diff once this is tested and
working.
> [DM-29805] Enable GCE persistent disk CSI driver on data-dev

- environment/deployments/science-platform/env/integration-gke.tfvars
- environment/deployments/science-platform/env/production-gke.tfvars
We want to use the GCE Physical Disk CSI driver for Redis storage
for Gafaelfawr because it supports snapshots.  Enable it on int and
prod, matching the earlier change to enable it on dev.
> [DM-29085] Enable the GCE PD CSI driver on int and prod

- environment/foundation/1-org-b/1-org-b.tfvars
- Can manage roles and permissions for a project and all resources within the project.
> Grant role/owner for gcp_square_administratotrs

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/env/integration-gke.tfvars
- environment/deployments/science-platform/env/production-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- modules/cloudsql/postgres-sql/main.tf
- modules/cloudsql/postgres-sql/variables.tf
postgres-private attempts to set up a private networking resource
that is already managed by the separate CloudSQL deployment, and
therefore conflicts.  Enhance postgres-sql to take the same new
parameters we're using and use it instead, and directly create the
service account (since this conceptually isn't part of the database
anyway).
> [DM-28120] Use postgres-sql for RSP database instance

- environment/deployments/science-platform/env/production.tfvars
We need sqladmin.googleapis.com for Cloud SQL Auth Proxy.  Make
this match the other two environments.
> [DM-28120] Activate more APIs in science-platform prod

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Test backup configuration in preparation for enabling it on int
and prod.
> [DM-29925] Enable science-platform database backups on dev

- environment/deployments/science-platform/env/integration-cloudsql.tfvars
- environment/deployments/science-platform/env/production-cloudsql.tfvars
This seemed to work properly on dev, so apply the same Terraform
configuration for Google IAM bindings for the gafaelfawr service
account to int and prod.
> [DM-29976] Apply gafaelfawr IAM config to int and prod

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
- environment/deployments/data-curation/variables.tf
Initial pipeline failed on the google group. We wanted the group to stay, so I removed it from tfstate and now removing any reference to it in the tf manifests.
> removed reference to Google Group module

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
We need to support more than 25 simultaneous connections to the
Gafaelfawr database to support load.  This is only possible with
a somewhat larger database instance.
> [DM-30880] Bump shared Science Platform database size

- environment/deployments/science-platform/env/integration-gke.tfvars
The fixed version of Kubernetes with an updated Calico layer has
not yet been released.
> Disable NetworkPolicy support on data-int

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
- modules/gke/main.tf
- modules/gke/readme.md
- modules/gke/variables.tf
We have to have 48 hours of maintenance in any 32 day interval, so
satisfy that with 12 hours per week.  Plumb the maintenance_*
settings through the module so that they can be set per environment.
data-dev will use midnight to noon UTC Wednesday (5pm to 5am PDT
Tuesday to Wednesday), and (later) int will do the same Thursday
and prod Friday.
> [DM-32180] Set maintenance window for data-dev GKE

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
The image cutout service requires a PostgreSQL database.  Add that
to the Terraform description of the science-platform CloudSQL
configuration along with the Kubernetes service account binding
required to access it.  Bump the serial number for the dev cluster
so that this change will be applied there.
> [DM-32386] Add vo-cutouts database

- environment/deployments/science-platform/env/integration-gke.tfvars
Fixes a typo in the Kafka nodepool declaration. They're getting e2-mediums right now, which are very small.
> Fix typo in Kafka nodepool declaration

- environment/deployments/science-platform/env/integration-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
- modules/gke/main.tf
- modules/gke/variables.tf
This change adds a taint to the Kafka node pool on the science-platform GKE, integration environment. The taint will help avoid scheduling non-Kafka work onto Kafka nodes.
This required passing the taints through two layers - the modules/gke module, and the environments/science-platform/gke module. I've used exactly the same variable name and type as the upstream terraform-google-kubernetes-engine module.
> DM-32568: Add taints to the Kafka node pool on data-int

- environment/deployments/science-platform/alertdb/main.tf
- environment/deployments/science-platform/alertdb/variables.tf
- environment/deployments/science-platform/env/dev-alertdb.tfvars
- environment/deployments/science-platform/env/integration-alertdb.tfvars
- environment/deployments/science-platform/env/production-alertdb.tfvars
Follow-up after failed runs https://github.com/lsst/idf_deploy/runs/4552457540 and https://github.com/lsst/idf_deploy/runs/4552457535 - we need to include environment (and more) in bucket names to make them unique.
> Use bucket names which are more likely to be unique

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
This is rather unfortunately mixed in with CloudSQL because it
needs to reuse the service account created for PostgreSQL access
for GCS bucket access as well.  Object creation access is granted
to the same service account as is currently used for Butler access.
This is temporary until we have client/server Butler.
> [DM-33494] Add GCS bucket for cutouts

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
We're using workload identity to bind a GKE service account to the
Google service account for vo-cutouts, which in addition to having
Cloud SQL access also has GCS access and needs to be able to
generate signed GCS URLs.
To do URL signing, it must have a private key, but exporting the
private key of a Google service account is deprecated and less secure,
and workload identity does not provide the private key.  The
alternative is to grant the service account the ability to create
tokens for itself (via the role iam.ServiceAccountTokenAccess), which
allows it to use its GKE credentials to bootstrap to a private key
that in turn can generate a pre-signed URL.
Enable this on dev and int.  Tested by manually creating the
equivalent policy on int.
> [DM-33494] Add additional IAM binding for vo-cutouts account

- environment/deployments/panda/env/dev.tfvars
Role scope only available at bucket level
> Removed legacy cloud storage role

- environment/deployments/science-platform/env/production-cloudsql.tfvars
Bump the serial number of the prod Cloud SQL environment so that
the vo-cutouts database, GCS bucket, service account, and service
and service account bindings will be created there.
> [DM-33720] Deploy vo-cutouts resources in IDF prod

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Times Square is a new RSP service for displaying templated notebooks as webpages, https://sqr-062.lsst.io. It requires a Cloud SQL db as a durable datastore for page settings.
Within the science-platform deployment:
- Added times-square database
- Added times-square db user
- Added times-square service account
- Added times-square-iam-binding
- Incremented deployment serial number
(This PR is parroting existing settings; let me know if they don't make sense!). Times Square will be deployed in a `times-square` Kubernetes namespace.
> DM-33753: Add times-square Cloud SQL DB

- environment/deployments/data-curation/env/production.tfvars
Terraform action of the last merge https://github.com/lsst/idf_deploy/pull/423 
failed probably because the bucket didn't exist at the time. Try again.
> DM-34729: Fix IAM policy for the bucket butler-us-central1-dp02-user

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/main.tf
The GKE Terraform runner doesn't have permissions to create service
accounts.  Move the service account to the science-platform top level
next to the GAR cachemachine service account and use a similar
construction to set it up.
> [DM-35029] Move hips service account out of GKE

- environment/deployments/data-curation/env/production.tfvars
Apply previous change to add the crawlspace-hips service account
to the ACL on the VISTA HiPS bucket.
> [DM-35028] Update data-curation

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
- environment/deployments/data-curation/variables.tf
- environment/deployments/science-platform/env/integration.tfvars
Use the naming convention discussed on Slack.  Grant RW access to
the Butler service account we've been using for ease of importing
data (the plan is to remove that access once the data is imported).
Create the crawlspace service account for data-int and add it to
the HiPS ACL list.
> [DM-35171] Add HiPS bucket for DP0.2

- environment/deployments/qserv/env/production.tfvars
Hi @dspeck1 , I added a missing fw rule for `qserv-prod`, for "QServ Operator Connectivity", it exists on `qserv-dev` and `qserv-int` but was missing on `qserv-prod`. I think this is a blocker for @fritzm because it prevents Qserv upgrade on  `qserv-prod`. Could you please review it ASAP?
Kind regards
> Add missing fw rule for QServ Operator Connectivity

- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/main.tf
This will eventually allow us to use workload identity to access
Butler, although that will require some additional setup of the
ACLs in the data-curation project.
> [DM-35248] Add Google service account for datalinker

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/variables.tf
Also move the account list out of variables.tf and into
production.tfvars, since it's really per-environment configuration
(even though that doesn't matter at the moment for data-curation).
> Add stable service account to HiPS bucket ACLs

- environment/deployments/science-platform/firestore/env/dev.tfvars
- environment/deployments/science-platform/firestore/main.tf
I think this has to exist in the Firestore project, not in the
Gafaelfawr service account project.
> [DM-34613] Create Gafaelfawr IAM binding in Firestore project

- .github/workflows/rsp-stable-firestore-proj-tf.yaml
- environment/deployments/science-platform/firestore/env/production.tfvars
In preparation for switching to COmanage and CILogon for the data.lsst.cloud environment, create a Firestore project for UID and GID tracking following the pattern used for dev and int.
> DM-37189: Add Firestore project for stable

- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/main.tf
The new Nublado lab controller needs to be able to talk to Google Artifact Registry and therefore needs a service account with workload identity enabled.
> DM-38279: Create service account for nublado controller

- environment/deployments/roundtable/env/dev-gke.tfvars
- environment/deployments/roundtable/env/production-gke.tfvars
These node pools include taints to ensure that only Kafka or Zookeeper processes run on these nodes.
> DM-39014: Add dedicated Kafka and Zookeeper node pools in Roundtable

- environment/deployments/panda/env/dev.tfvars
- environment/deployments/panda/main.tf
- environment/deployments/panda/variables.tf
To give data-dev.lsst.cloud the same access to the Butler database used by data-int.lsst.cloud as that environment, grant the service account used by the Cloud SQL Proxy running on data-dev the cloudsql.client role.
> Add Butler database access for data-dev

- environment/deployments/panda/variables.tf
When granting data-dev access to the panda-dev Butler, add the missing serviceAccount prefix to the service account name.
> Add serviceAccount prefix for Butler access

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
- environment/deployments/data-curation/variables.tf
- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/env/production.tfvars
- environment/deployments/roundtable/main.tf
Add a Git LFS storage bucket in data-curation-prod and add service accounts to access it RO and RW in roundtable-prod.
> tickets/DM-41550: Add Git LFS objects

- .gitignore
- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/env/production.tfvars
- environment/deployments/roundtable/main.tf
The giftless implementation uses signed URLS; hence we must allow the SA to sign.
> tickets/DM-41550B: allow git lfs accounts to sign

- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/main.tf
This should create a new service account in each environment, assign it the file.editor role, and bind it to the filestore-backup SA in the K8s namespace of the same name.
> Add Workload Identity mappings for filestore backup

- environment/deployments/roundtable/cloudsql/main.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
The separate gafaelfawr-tokens service account no longer needs IAM bindings, since the other components of Gafaelfawr now use a stand-alone Cloud SQL Proxy that uses the same service account as Gafaelfawr. Add a gafaelfawr-schema-update service account with Cloud SQL access, since it will be used to do schema migrations.
> DM-42384: Update Gafaelfawr service accounts

- environment/deployments/roundtable/cloudsql/main.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/main.tf
- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Use google_service_account_iam_member instead of
google_service_account_iam_binding to set up workload identity. Narrow the grant of bindings for the vault and git-lfs service accounts to just the Google service accounts they should be using.
> DM-42714: Convert to new workload identity setup

- .github/workflows/rsp-demo-gke-tf.yaml
- .github/workflows/rsp-demo-proj-tf.yaml
- NEW_ENVIRONMENT.md
use more limited keys for demo GHA
> tickets/DM-43454-foundation: use more limited keys for demo GHA

- README.md
- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Added SSO UWS database to CloudSQL on the dev project.
I've named the new database ssotap-uws. Alternatives were "sso-tap-uws" and "ssotap", but I wanted to match the application name, and then add "-uws" to it in case we want to add other databases for that application later.
Updated the serial number dev-cloudsql.tfvars
Also fixed a couple typos in the README
> Added ssotap uws database in CloudSQL / Fixed typo

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
vo-cutouts now does everything with its own credentials and workload identity and no longer uses the Butler service account. Grant it legacyBucketWriter as well (for some reason, we need the legacy version or the backend code doesn't work).
> DM-44606: Update permissions for vo-cutouts

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
**Description**
We're creating a cloudSQL resource for the UWS database for the TAP service. Previously we did the same for the SSO TAP, which seems to be working as expected, so now doing the same for the main TAP.
**What envs are affected:**
- idfdev
**Other Notes**
We use "tap" as the database name. We then create a uws schema in that database in the application side and we can later add other schemas like (TAP_SCHEMA) to it.
> Create TAP cloudsql database on dev

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
**Description**
My last change to use obstap was incorrect, as the Kubernetes namespace and serviceAccount need to be "tap" (i.e. match the app name)
> Change cloudsql config name from obstap to tap

- environment/deployments/science-platform/env/integration-cloudsql.tfvars
Deploy vo-cutouts permission changes and the new ssotap database on idfint. The vo-cutouts permission changes are required for the 2.0.0 release, which uses workload identity and no longer uses the Butler credentials.
This change also applies the changes in f1bd4fc89ec4d879c657e2d3def87eb4725131eb to use a better approach to configuring workload identity.
- idfint
Examined the Terraform plan, which looks correct. Due to the change in how workload identity is specified, there is a lot of resource churn since the old bindings have to be deleted and replaced with the new bindings.
> DM-44606: Deploy recent changes to idfint

- environment/deployments/science-platform/env/production-cloudsql.tfvars
Trigger a Terraform run on the idfprod environment to update vo-cutout permissions, create new databases for tap and ssotap, and switch the way that IAM bindings are done in Terraform. This has already been tested on idfdev and idfint.
> DM-44606: Deploy recent changes to idfprod

- environment/deployments/science-platform/firestore/env/production.tfvars
Fix label to be appended with firestore in name.   This updates it to reflect same naming as dev and int.
> RSP Firestore Stable Label Fix

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
An old version of the Butler used by some tutorial notebooks needs 'GetBucketLocation' permission to check for the existence of buckets at startup.  DM-46701 made more buckets part of the configuration that gets verified at startup, and these buckets don't have that configuration set.
> DM-46890: Add bucket metadata permissions for DP02

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
wobbly is the new UWS storage service that all UWS-pattern applications written internal to Rubin will use. Allocate a CloudSQL database and service account for it.
> DM-47262: Add wobbly database and service account

- .github/workflows/rsp-int-cloudsql-tf.yaml
- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
Changes to support terraform and google module upgrade.  Add conditionals and default values for Butler DP02 Registry so that registry is not created as part of this ticket and can be conditionally created per environment.  The terraform state was updated for the cutouts bucket so that the bucket is not destroyed.  The plan output shows that CloudSQL passwords are updated.  From testing in dev this is only the terraform state values and does not update CloudSQL passwords.  Note that passwords from terraform are not used.  CloudSQL users are created via terraform then the passwords are reset via the console.  Application connectivity from RSP to CloudSQL should be validated though after this change just in case.
> DM-47492:  CloudSQL Int

- .github/workflows/alerts-dev-gke-tf.yaml
- .github/workflows/alerts-dev-proj-tf.yaml
Update google cloud action to newer action.  The current one was depreciated.  This is the first commit on two unused GHAs to test the process and make sure there are no side effects.
> DM-43915:  GCP GHA Update 1

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
Add Postgres 16 DB for the DP02 Butler to data-int.  Moved some configuration out of the tfvars file into the defaults so it can be shared between all the environments.
Also added domain names that can be used for referencing the databases from Phalanx configuration.
Added a 'moved' block to prevent terraform from destroying the `data-dev` DB.  The terraform code for this DB had changed since data-dev was last deployed.
> Set up Postgres 16 DP02 butler SQL on data-int

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
It turns out that Google Cloud will not allow two managed zones to have the same name even if they are in different projects.
> DM-45901: Make DNS zone name unique for each environment

- environment/deployments/science-platform/env/production-cloudsql.tfvars
Enable the Postgres 16 Butler DB for DP02 on `science-platform-stable`.
> DM-45901: Set up DP02 Butler DB on idfprod

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Add a Cloud SQL instance to use as the Butler Registry database for Data Preview 1 on the development environment.
> DM-48589: Add Butler database for Data Preview 1 on idfdev

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
Add a GCS bucket that will be used to hold the preliminary version of Data Preview 1, until infrastructure at USDF is available for hosting it.
The IAM accounts for this bucket are separate from the previous credentials -- unlike previous data previews, end users will not have direct S3 access to the bucket.
> DM-48589: Add GCS bucket for Data Preview 1

- environment/deployments/science-platform/env/integration-cloudsql.tfvars
- environment/deployments/science-platform/env/production-cloudsql.tfvars
Add a Cloud SQL instance to use for Data Preview 1 on the integration and production environments.
> DM-48589: Enable Butler DP1 database for int and prod

- environment/deployments/roundtable/cloudsql/main.tf
Add configuration for a new Cloud SQL user and service account for the "ook" Cloud SQL database in the Roundtable clusters.
> DM-49491: Provision Cloud SQL for Ook

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Previously, Cloud SQL access was done via a separate Cloud SQL Proxy pod that used the `gafaelfawr` service account, but we now want to use sidecar containers for the proxy uniformly. Grant direct Cloud SQL access to the separate `gafaelfawr-operator` Kubernetes service account.
Delete the permissions for `gafaelfawr-schema-update`, since the schema update `Job` now uses the regular `gafaelfawr` service account.
> DM-49524: Give gafaelfawr-operator direct Cloud SQL access

- environment/deployments/roundtable/cloudsql/main.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
- environment/deployments/roundtable/env/production-cloudsql.tfvars
Remove the workload identity binding for Gafaelfawr for the Kubernetes service account gafaelfawr-update-schema on Roundtable because it's no longer used. Add a binding for gafaelfawr-operator, since we're now going to use sidecar containers instead of a stand-alone Cloud SQL Proxy instance.
> DM-49524: Change Gafaelfawr service accounts on Roundtable

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
This DB was never used.
Will fully remove the terraform associated with it in a later commit -- want to make sure it tears down cleanly before applying to `-int` and `-stable`.
> DM-48684: Disable science-platform-dev legacy Butler database

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
- modules/cloudsql/postgres-private/main.tf
The other science-platform databases are implicitly depending on private services access networking setup that was being created by the private-postgres module removed in DM-48684b.  Hoist the networking setup to the top level of the module so it isn't deleted.
> DM-48684: Move SQL private service access to top level

- environment/deployments/panda/cloudsql/main.tf
- environment/deployments/panda/cloudsql/variables.tf
- environment/deployments/panda/env/dev-cloudsql.tfvars
Fix an issue where Private Service Access setup for the VPC could not be torn down during terraform deployment.
> DM-48684: Fix panda-dev deployment failure

- environment/deployments/science-platform/env/integration-cloudsql.tfvars
Remove a Butler database from science-platform-int that has never been used for DP02, but may have been used for some other purposes.
> DM-48684: Remove unused science-platform-int DB

- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Upgrade the CloudSQL database for the idfdev Science Platform to PostgreSQL 14 from PostgreSQL 13.
> DM-49696: Upgrade the idfdev science-platform CloudSQL

- environment/deployments/roundtable/cloudsql/variables.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
Continue the upgrades of our Cloud SQL databases by changing the default version for roundtable clusters to PostgreSQL 15 and triggering the update on roundtable-dev.
> DM-49696: Upgrade roundtable-dev Cloud SQL to PostgreSQL 15

- .github/workflows/roundtable-prod-proj-tf.yaml
- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/env/production.tfvars
- environment/deployments/roundtable/main.tf
- environment/deployments/roundtable/outputs.tf
- environment/deployments/roundtable/variables.tf
[Prodromos](https://github.com/lsst-sqre/prodromos) is a new project that contains terraform config for configuring Sentry for Phalanx projects.
These resources are provisioned to support that project:
* GCS bucket to keep the terraform state
* Workload Identity Provider to federate auth from GitHub via OIDC
* Service account that has read/write access on the bucket
* Workload Identity Federation to allow the [Atlantis service](https://github.com/lsst-sqre/phalanx/pull/4467) in the roundtable clusters to impersonate that service account and read and write objects in the state bucket
https://github.com/lsst/idf_deploy/pull/584 was the initial version of this work when we were planning on running Terraform in GitHub actions. We later decided to try running the Terraform with …
> DM-44145: Prodromos (sentry config) terraform bucket and auth - Atlantis version

- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
Upgrade the general-purpose science-platform Cloud SQL database for idfdev to PostgreSQL 16.
> DM-49696: Upgrade idfdev Cloud SQL to PostgreSQL 16

- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/cloudsql/variables.tf
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
- modules/alloydb/main.tf
- modules/alloydb/variables.tf
Set up an AlloyDB cluster to be used as the Butler registry for data previews, initially deployed to data-int.
This also captures an out-of-terraform configuration change to increase `max_connections` for the `science-platform` to 1000 from 100.
> DM-50677: Initial AlloyDB setup for Butler registry

- environment/deployments/roundtable/cloudsql/variables.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
Upgrade the Cloud SQL version for roundtable to PostgreSQL 16 and apply Terraform to the roundtable-dev cluster.
> DM-49696: Upgrade roundtable-dev to PostgreSQL 16

- environment/deployments/science-platform/env/production-cloudsql.tfvars
Set up an AlloyDB instance for `idfprod`, which will initially be used for hosting DP1 and may eventually also contain DP0.2 and DP2.
> DM-50677e: Set up Butler AlloyDB in production

- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/main.tf
Add service account and workload identity permissions for EUPS Distributor.  A service account named `eups-distributor` will need to be added to roundtable Kubernetes.
> Add EUPS Distributor Workload Identity

- environment/deployments/roundtable/env/production-gke.tfvars
Bump serial to deploy FUSE to GKE.  Note that terraform apply takes ~50 minutes.  The node pools and applications stay up.  The time is spent updating the GKE control plane to install the FUSE CSI driver.  The deletion of the monitoring and logging service account is normal.  The access is built into GKE now so not needed.
The state was already fixed and validated with a manual terraform plan.
> Enable FUSE for EUPS on Roundtable Prod

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
- modules/gke/main.tf
- modules/gke/variables.tf
Bump serial after state cleaned up for terraform upgrade.  In the terraform plan the Filestore CSI driver will be disabled.  The Filestore CSI drive does not appear to be used since no PVs use the filestore CSI storage classes.  The Filestore CSI is not enabled on int or prod.  @athornton  - please confirm that the filestore CSI driver is ok to disable?  If not can add I can add it to terraform.
```
~ addons_config {
~ gcp_filestore_csi_driver_config {
~ enabled = true -> false
}
```
> DM-47402 RSP GKE Dev Terraform Upgrade

- environment/deployments/science-platform/env/dev-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
- environment/deployments/science-platform/gke/variables.tf
- modules/gke/main.tf
- modules/gke/variables.tf
* Modify the `gke` module to:
* Provide options for enabling GCP's [Managed Service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus)(MSP)
* Allow enabling automatic collection of premium cluster metrics, like kube state metrics and kubelet metrics
* Enable MSP for the idfdev cluster
* Enable collection of kube state metrics (for OOM kill monitoring), kublet metrics (for PVC disk usage monitoring), and cadvisor metrics (for CPU throttling monitoring)
> DM-50932: Support for Google Clould Managed Service for Prometheus

- environment/deployments/roundtable/cloudsql/main.tf
- environment/deployments/roundtable/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/cloudsql/main.tf
- environment/deployments/science-platform/env/dev-cloudsql.tfvars
- environment/deployments/science-platform/env/integration-cloudsql.tfvars
Grafana will be deployed in every Phalanx env.
It can use a SQLite DB, but:
* It doesn't work very well over networked storage
* It won't scale if Grafana gets a lot of usage, and we'll have to move to Postgres eventually anyway
* Alerting functionality works better with a Postgres instance
Eventually we want a separate database instance for Grafana so that we don't lose grafana when this database instance is under pressure (which is one situation where we will probably want it most), but let's just get it off the ground for DP1.
> DM-50602: Grafana Postgres DB

- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/main.tf
- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/env/integration.tfvars
- environment/deployments/science-platform/main.tf
This will let us query our Google Cloud Monitoring metrics from our in-cluster Grafana instance.
It's possible that the `member` attribute has to be the k8s service account identifier variety, but I don't think so. I'll find out after this is applied :)
> DM-51084: Give grafana SA monitoring.viewer (lower envs)

- environment/deployments/science-platform/env/dev-gke.tfvars
The managed collection of pod metrics [doesn't include kube_pod_container_status_last_terminated_reason or kube_pod_container_status_restarts_total](https://issuetracker.google.com/issues/418169221), which is the best way to alert on OOM kills by pod and container name. So, we have to run our own kube-state-metrics exporter to provide pod metrics. This PR disables the managed kube-state-metrics collectors we won't get double metrics when we're running our own kube-state-metrics exporter.
> DM-50932: Don't collect pod metrics with managed kube-state-metrics

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
Set up a bucket to store the Data Preview 1 HiPS maps, with access granted to the crawlspace service account.
> DM-51280: Add a bucket for DP1 HiPS

- environment/deployments/science-platform/env/integration-gke.tfvars
- environment/deployments/science-platform/gke/main.tf
Upgrade after terraform provider upgrade and state cleanup.  The account deletion is normal.  Temporarily added Security Admin to pipeline Terraform account to delete unused monitoring and logging service accounts.  Remember to remove role after deploying.
> DM-47402 RSP GKE Int Terraform Provider Upgrade

- environment/deployments/data-curation/env/production.tfvars
- environment/deployments/data-curation/main.tf
Disable a Butler service account that is no longer used, and which has had its credentials provided to end users.
Give a private Butler server service account access to the dp02-users bucket, which it was formerly using the other account to access.
> DM-51374: Disable end-user Butler service account

- environment/deployments/roundtable/env/dev.tfvars
- environment/deployments/roundtable/env/production.tfvars
- environment/deployments/roundtable/main.tf
- environment/deployments/roundtable/variables.tf
- environment/deployments/science-platform/env/dev.tfvars
- environment/deployments/science-platform/env/integration.tfvars
- environment/deployments/science-platform/env/production.tfvars
- environment/deployments/science-platform/main.tf
- environment/deployments/science-platform/variables.tf
The terraform config for provisioning Google Cloud monitoring resources is going to live in [Prodromos](https://prodromos.lsst.io), because Prodromos is the place where we're experimenting with using Terraform to provision monitoring resources.
The Terraform config in Prodromos gets provisioned using [Atlantis](https://runatlantis.io), specifically the Atlantis instance in `roundtable-prod`.
To provision Google Cloud monitoring resources via Atlantis, the Google Cloud service account that is federated with the Atlantis pod service account must have `monitoring.admin` powers in ALL of the projects that we Atlantis to provision.
> DM-51219: Roundtable Atlantis instance monitoring.admin in all projects
